export type TabId = 'home' | 'display' | 'mirroring' | 'control' | 'apps' | 'files' | 'system' | 'settings';
export type { ToolStatus, ToolsStatus } from '../../context/tools.svelte';
export type WorkTab = Exclude<TabId, 'home'>;
export type AppSummary = { package_name: string; display_name: string; apk_path: string; system_app: boolean; disabled: boolean; uninstalled: boolean; icon_data_url: string };
export type AppPermissionInfo = { name: string; granted: boolean; runtime: boolean; changeable: boolean };
export type AppDetailsInfo = AppSummary & { is_split: boolean; version_name: string; version_code: string; target_sdk: string; min_sdk: string; installer: string; data_dir: string; code_size_bytes: number; data_size_bytes: number; cache_size_bytes: number; background_mode: string; permissions: AppPermissionInfo[]; install_date: string; update_date: string };
export type StorageSizes = {
  data_size_bytes: number;
  cache_size_bytes: number;
};
export type AppFilter = 'user' | 'all' | 'system' | 'disabled' | 'uninstalled' | 'debloat';
export type FileEntry = { name: string; permissions: string; size: number; modified: string; is_directory: boolean; is_link: boolean; link_target: string };
export type FileView = 'list' | 'grid';
export type FileSortKey = 'name' | 'type' | 'size' | 'permissions' | 'modified';
export type MediaVolumeState = { level: number; maximum: number };
export type MirrorMode = 'display' | 'virtual' | 'camera';
export type SoundMode = 'NORMAL' | 'VIBRATE' | 'SILENT';
export type AndroidUser = { id: number; name: string; is_running: boolean };
export type KeyboardInputMethod = { id: string; label: string; enabled: boolean; is_default: boolean };
export type SystemState = { users: AndroidUser[]; current_user_id: number; gestural_navigation: boolean; app_languages_enabled: boolean; captive_portal_mode: string | null; keyboards: KeyboardInputMethod[]; current_keyboard_id: string };
